/var/log/kafka-connect/restart_connectors.log {
    daily
    maxsize 20M
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    dateext
    dateformat -%Y%m%d
}
